### ISSUE TITLE
Custom probe endpoints?

### ISSUE THREAD

**Issue by BaiqingL** [leondz/garak#137]
Is it possible right now to create a custom endpoint that accepts some function like `inference(input)` and expect a string output which can then be used to evaluate? This would allow people who develop custom LLMs to use this tool and test it via a set of standard definitions.

**Comment by leondz** [comment]
Sounds like a good idea. To clarify, do you mean that `inference(input)` calls some external function, maybe an LLM, with the input, and the returned value is the LLM's output? In this case, this could be implemented as a `generator` in garak. 

I wonder, what kind of parameter should be passed, perhaps a module path and function? Maybe something like `..module.path#function`.

What kind of types do you think would fit? `inference(input: str) -> str` seems the minimal case, though it'd be good if generation parameters like number of outputs, and temperature, could go as well. Perhaps as arguments in a dict packaged in a separate generator.

In this case, the proposed API could be:

`garak.generators.function.BasicSingle`, taking a parameter like `"module.path#function"`
will import `module.path` and call `function` with `function(prompt: str) -> str` in order to get generations

`garak.generators.function.WithParams`, taking a parameter like `"module.path#function"`
will import `module.path` and call `function` with `function(prompt: str, parameters: dict) -> List(str)`
where `parameters` has keys like `generations`, `temperature`, `max_len`, `top_k` etc
and the length of the returned list is determined by `parameters["generations"]`

Would this work for you?

**Comment by BaiqingL** [comment]
Since each model may have different parameters, it may be better off to just pass the extra arguments in some fashion like `inference(input, **inference_args)`.

And yes! Your proposal sounds great :)

**Comment by leondz** [comment]
prototype added in #176 and merged, let me know how it is, feel free to send a PR if you need some more :)

**Comment by BaiqingL** [comment]
Looks good! Thanks for the support
